# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import zlm.validators


class Migration(migrations.Migration):

    dependencies = [
        ('zlm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlmurl',
            name='url',
            field=models.CharField(max_length=220, validators=[zlm.validators.validate_url, zlm.validators.validate_com]),
        ),
    ]
